<?php

require_once dirname(__DIR__) . '/vendor/autoload.php';

use \GuzzleHttp\Client;



class CheckTest extends \PHPUnit\Framework\TestCase
{
	/**
	 * @var Client
	 */
	private $client;

	public function setUp(): void
	{
		$this->client = new Client([
			// Base URI is used with relative requests
			'base_uri' => 'http://localhost:8080',
			'timeout'  => 2.0,
		]);
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function testPOST()
	{
		// Client sample
		$data = array(
			'' => 'test',
			'avatarNumber' => 5,
			'tagLine' => 'a test dev!'
		);

		$response = $this->client->post('/v1/check', ['body' => json_encode($data)]);

		$this->assertIsNotInt($response);
	}
}
